#include <QtGui>
#include <QGraphicsItem>
#include <QMenuBar>
#include <QLineEdit>
#include <QBoxLayout>
#include <QTreeWidget>
#include <QWidgetAction>
#include <QHeaderView>
#include <QGraphicsScene>
#include <QOpenGLContext>