%token             IDENTIFIER TYPE STRLIT VAL
%%
Prop:              Body ")""]" "uniform" TYPE IDENTIFIER OptDef;
OptDef:            |"=" Value ";";

Body:              "property" BodyLast;
BodyFirst:         Min | Max | Name;
BodyLast:          |"," BodyFirst BodyLast;

Min: "Min" "=" Value;
Max: "Max" "=" Value;
Name: "Name" "=" STRLIT;

Value: VAL | "{" ValueFirst ValueRest "}";
ValueFirst: VAL;
ValueRest: |"," Value;